list = """
Apple Inc.(AAPL      )
Microsoft Corp.(MSFT      )
Amazon.com Inc.(AMZN      )
Facebook Inc. Class A(FB        )
Alphabet Inc. Class A(GOOGL     )
Alphabet Inc. Class C(GOOG      )
Tesla Inc.(TSLA      )
NVIDIA Corp.(NVDA      )
Berkshire Hathaway Inc. Class B(BRK.B     )
JPMorgan Chase & Co.(JPM       )
Johnson & Johnson(JNJ       )
UnitedHealth Group Inc.(UNH       )
Visa Inc. Class A(V         )
Procter & Gamble Co.(PG        )
Home Depot Inc.(HD        )
PayPal Holdings Inc.(PYPL      )
Walt Disney Co.(DIS       )
Adobe Inc.(ADBE      )
Bank of America Corp.(BAC       )
Mastercard Inc. Class A(MA        )
Comcast Corp. Class A(CMCSA     )
Pfizer Inc.(PFE       )
salesforce.com Inc.(CRM       )
Netflix Inc.(NFLX      )
Cisco Systems Inc.(CSCO      )
Exxon Mobil Corp.(XOM       )
Verizon Communications Inc.(VZ        )
Abbott Laboratories(ABT       )
Coca-Cola Co.(KO        )
Intel Corp.(INTC      )
Thermo Fisher Scientific Inc.(TMO       )
PepsiCo Inc.(PEP       )
Accenture plc Class A(ACN       )
AbbVie Inc.(ABBV      )
NIKE Inc. Class B(NKE       )
Danaher Corp.(DHR       )
Eli Lilly & Co.(LLY       )
Walmart Inc.(WMT       )
Broadcom Inc.(AVGO      )
Costco Wholesale Corp.(COST      )
AT&T Inc.(T         )
Merck & Co. Inc.(MRK       )
Wells Fargo & Co.(WFC       )
Chevron Corp.(CVX       )
Medtronic plc(MDT       )
McDonald's Corp.(MCD       )
Texas Instruments Inc.(TXN       )
QUALCOMM Inc.(QCOM      )
NextEra Energy Inc.(NEE       )
Linde plc(LIN       )
Oracle Corp.(ORCL      )
Honeywell International Inc.(HON       )
Philip Morris International Inc.(PM        )
Morgan Stanley(MS        )
Intuit Inc.(INTU      )
Bristol-Myers Squibb Co.(BMY       )
Citigroup Inc.(C         )
Lowe's Cos. Inc.(LOW       )
Union Pacific Corp.(UNP       )
United Parcel Service Inc. Class B(UPS       )
Goldman Sachs Group Inc.(GS        )
Starbucks Corp.(SBUX      )
Advanced Micro Devices Inc.(AMD       )
BlackRock Inc.(BLK       )
American Tower Corp.(AMT       )
Amgen Inc.(AMGN      )
Raytheon Technologies Corp.(RTX       )
ServiceNow Inc.(NOW       )
International Business Machines Corp.(IBM       )
Intuitive Surgical Inc.(ISRG      )
Applied Materials Inc.(AMAT      )
Target Corp.(TGT       )
Boeing Co.(BA        )
Deere & Co.(DE        )
General Electric Co.(GE        )
Caterpillar Inc.(CAT       )
Moderna Inc.(MRNA      )
CVS Health Corp.(CVS       )
3M Co.(MMM       )
Charter Communications Inc. Class A(CHTR      )
Charles Schwab Corp.(SCHW      )
American Express Co.(AXP       )
S&P Global Inc.(SPGI      )
Prologis Inc.(PLD       )
Zoetis Inc.(ZTS       )
Booking Holdings Inc.(BKNG      )
Altria Group Inc.(MO        )
Anthem Inc.(ANTM      )
Gilead Sciences Inc.(GILD      )
Stryker Corp.(SYK       )
Automatic Data Processing Inc.(ADP       )
Lockheed Martin Corp.(LMT       )
TJX Cos. Inc.(TJX       )
Analog Devices Inc.(ADI       )
Mondelez International Inc. Class A(MDLZ      )
Lam Research Corp.(LRCX      )
Crown Castle International Corp.(CCI       )
Chubb Ltd.(CB        )
Micron Technology Inc.(MU        )
PNC Financial Services Group Inc.(PNC       )
Duke Energy Corp.(DUK       )
T-Mobile US Inc.(TMUS      )
Marsh & McLennan Cos. Inc.(MMC       )
Fidelity National Information Services Inc.(FIS       )
Estee Lauder Cos. Inc. Class A(EL        )
US Bancorp(USB       )
Truist Financial Corp.(TFC       )
Equinix Inc.(EQIX      )
ConocoPhillips(COP       )
Capital One Financial Corp.(COF       )
CSX Corp.(CSX       )
Becton Dickinson and Co.(BDX       )
Edwards Lifesciences Corp.(EW        )
Sherwin-Williams Co.(SHW       )
Cigna Corp.(CI        )
CME Group Inc.(CME       )
Regeneron Pharmaceuticals Inc.(REGN      )
Fiserv Inc.(FISV      )
Southern Co.(SO        )
Autodesk Inc.(ADSK      )
Intercontinental Exchange Inc.(ICE       )
Eaton Corp. plc(ETN       )
Illinois Tool Works Inc.(ITW       )
Illumina Inc.(ILMN      )
HCA Healthcare Inc.(HCA       )
Colgate-Palmolive Co.(CL        )
FedEx Corp.(FDX       )
Aon plc Class A(AON       )
Boston Scientific Corp.(BSX       )
Activision Blizzard Inc.(ATVI      )
Norfolk Southern Corp.(NSC       )
Emerson Electric Co.(EMR       )
Dominion Energy Inc.(D         )
General Motors Co.(GM        )
Moody's Corp.(MCO       )
Waste Management Inc.(WM        )
Air Products & Chemicals Inc.(APD       )
NXP Semiconductors NV(NXPI      )
IDEXX Laboratories Inc.(IDXX      )
Progressive Corp.(PGR       )
Ecolab Inc.(ECL       )
Northrop Grumman Corp.(NOC       )
Johnson Controls International plc(JCI       )
Chipotle Mexican Grill Inc. Class A(CMG       )
Freeport-McMoRan Inc.(FCX       )
Agilent Technologies Inc.(A         )
Dollar General Corp.(DG        )
Humana Inc.(HUM       )
MSCI Inc. Class A(MSCI      )
KLA Corp.(KLAC      )
Vertex Pharmaceuticals Inc.(VRTX      )
Twitter Inc.(TWTR      )
DexCom Inc.(DXCM      )
Ford Motor Co.(F         )
Align Technology Inc.(ALGN      )
Biogen Inc.(BIIB      )
Roper Technologies Inc.(ROP       )
T. Rowe Price Group Inc.(TROW      )
Synopsys Inc.(SNPS      )
IQVIA Holdings Inc.(IQV       )
eBay Inc.(EBAY      )
TE Connectivity Ltd.(TEL       )
Public Storage(PSA       )
Global Payments Inc.(GPN       )
Exelon Corp.(EXC       )
L3Harris Technologies Inc.(LHX       )
Trane Technologies plc(TT        )
Carrier Global Corp.(CARR      )
Dow Inc.(DOW       )
American International Group Inc.(AIG       )
Kimberly-Clark Corp.(KMB       )
Newmont Goldcorp Corp.(NEM       )
Digital Realty Trust Inc.(DLR       )
MetLife Inc.(MET       )
General Dynamics Corp.(GD        )
Amphenol Corp. Class A(APH       )
Cadence Design Systems Inc.(CDNS      )
IHS Markit Ltd.(INFO      )
American Electric Power Co. Inc.(AEP       )
Bank of New York Mellon Corp.(BK        )
Simon Property Group Inc.(SPG       )
Microchip Technology Inc.(MCHP      )
Fortinet Inc.(FTNT      )
ResMed Inc.(RMD       )
Ross Stores Inc.(ROST      )
Prudential Financial Inc.(PRU       )
Sempra Energy(SRE       )
Electronic Arts Inc.(EA        )
O'Reilly Automotive Inc.(ORLY      )
Motorola Solutions Inc.(MSI       )
Aptiv plc(APTV      )
Sysco Corp.(SYY       )
Allstate Corp.(ALL       )
Cognizant Technology Solutions Corp. Class A(CTSH      )
Travelers Cos. Inc.(TRV       )
EOG Resources Inc.(EOG       )
DuPont de Nemours Inc.(DD        )
SBA Communications Corp. Class A(SBAC      )
Schlumberger Ltd.(SLB       )
Discover Financial Services(DFS       )
Yum! Brands Inc.(YUM       )
Baxter International Inc.(BAX       )
Parker-Hannifin Corp.(PH        )
Xilinx Inc.(XLNX      )
PPG Industries Inc.(PPG       )
Rockwell Automation Inc.(ROK       )
Marathon Petroleum Corp.(MPC       )
International Flavors & Fragrances Inc.(IFF       )
Otis Worldwide Corp.(OTIS      )
Xcel Energy Inc.(XEL       )
Paychex Inc.(PAYX      )
Centene Corp.(CNC       )
Welltower Inc.(WELL      )
Walgreens Boots Alliance Inc.(WBA       )
Mettler-Toledo International Inc.(MTD       )
Monster Beverage Corp.(MNST      )
Marriott International Inc./MD Class A(MAR       )
Aflac Inc.(AFL       )
HP Inc.(HPQ       )
Constellation Brands Inc. Class A(STZ       )
General Mills Inc.(GIS       )
Nucor Corp.(NUE       )
First Republic Bank/CA(FRC       )
Cintas Corp.(CTAS      )
Hilton Worldwide Holdings Inc.(HLT       )
Pioneer Natural Resources Co.(PXD       )
Cummins Inc.(CMI       )
Archer-Daniels-Midland Co.(ADM       )
AutoZone Inc.(AZO       )
TransDigm Group Inc.(TDG       )
West Pharmaceutical Services Inc.(WST       )
Equifax Inc.(EFX       )
American Water Works Co. Inc.(AWK       )
Keysight Technologies Inc.(KEYS      )
SVB Financial Group(SIVB      )
Verisk Analytics Inc. Class A(VRSK      )
Kroger Co.(KR        )
Corteva Inc.(CTVA      )
CBRE Group Inc. Class A(CBRE      )
Public Service Enterprise Group Inc.(PEG       )
McKesson Corp.(MCK       )
Fastenal Co.(FAST      )
AvalonBay Communities Inc.(AVB       )
ANSYS Inc.(ANSS      )
Kinder Morgan Inc./DE(KMI       )
Ameriprise Financial Inc.(AMP       )
Ball Corp.(BLL       )
Zebra Technologies Corp.(ZBRA      )
AMETEK Inc.(AME       )
DR Horton Inc.(DHI       )
Zimmer Biomet Holdings Inc.(ZBH       )
Stanley Black & Decker Inc.(SWK       )
Eversource Energy(ES        )
Phillips 66(PSX       )
Corning Inc.(GLW       )
Skyworks Solutions Inc.(SWKS      )
Copart Inc.(CPRT      )
WEC Energy Group Inc.(WEC       )
Laboratory Corp. of America Holdings(LH        )
Arthur J Gallagher & Co.(AJG       )
Southwest Airlines Co.(LUV       )
Lennar Corp. Class A(LEN       )
Equity Residential(EQR       )
Willis Towers Watson plc(WLTW      )
PACCAR Inc.(PCAR      )
Alexandria Real Estate Equities Inc.(ARE       )
CDW Corp./DE(CDW       )
Albemarle Corp.(ALB       )
Generac Holdings Inc.(GNRC      )
Etsy Inc.(ETSY      )
Old Dominion Freight Line Inc.(ODFL      )
Fifth Third Bancorp(FITB      )
Valero Energy Corp.(VLO       )
Realty Income Corp.(O         )
Weyerhaeuser Co.(WY        )
Synchrony Financial(SYF       )
Gartner Inc.(IT        )
Garmin Ltd.(GRMN      )
Republic Services Inc. Class A(RSG       )
Hershey Co.(HSY       )
Best Buy Co. Inc.(BBY       )
Delta Air Lines Inc.(DAL       )
LyondellBasell Industries NV Class A(LYB       )
Williams Cos. Inc.(WMB       )
Waters Corp.(WAT       )
United Rentals Inc.(URI       )
Kansas City Southern(KSU       )
ViacomCBS Inc. Class B(VIAC      )
Dover Corp.(DOV       )
Fortive Corp.(FTV       )
Extra Space Storage Inc.(EXR       )
Northern Trust Corp.(NTRS      )
Vulcan Materials Co.(VMC       )
VF Corp.(VFC       )
Xylem Inc./NY(XYL       )
Paycom Software Inc.(PAYC      )
Hartford Financial Services Group Inc.(HIG       )
State Street Corp.(STT       )
Martin Marietta Materials Inc.(MLM       )
Trimble Inc.(TRMB      )
Enphase Energy Inc.(ENPH      )
International Paper Co.(IP        )
ONEOK Inc.(OKE       )
Kraft Heinz Co.(KHC       )
DTE Energy Co.(DTE       )
Tyson Foods Inc. Class A(TSN       )
Cerner Corp.(CERN      )
Huntington Bancshares Inc./OH(HBAN      )
PPL Corp.(PPL       )
Nasdaq Inc.(NDAQ      )
Ameren Corp.(AEE       )
Tractor Supply Co.(TSCO      )
Charles River Laboratories International Inc.(CRL       )
Catalent Inc.(CTLT      )
Entergy Corp.(ETR       )
Cooper Cos. Inc.(COO       )
Mid-America Apartment Communities Inc.(MAA       )
Edison International(EIX       )
FleetCor Technologies Inc.(FLT       )
Occidental Petroleum Corp.(OXY       )
Teledyne Technologies Inc.(TDY       )
Essex Property Trust Inc.(ESS       )
McCormick & Co. Inc./MD(MKC       )
VeriSign Inc.(VRSN      )
Monolithic Power Systems Inc.(MPWR      )
Caesars Entertainment Inc.(CZR       )
Ulta Beauty Inc.(ULTA      )
Qorvo Inc.(QRVO      )
FirstEnergy Corp.(FE        )
Expeditors International of Washington Inc.(EXPD      )
Dollar Tree Inc.(DLTR      )
STERIS plc(STE       )
Ventas Inc.(VTR       )
Clorox Co.(CLX       )
PerkinElmer Inc.(PKI       )
Ingersoll Rand Inc.(IR        )
Church & Dwight Co. Inc.(CHD       )
Expedia Group Inc.(EXPE      )
CarMax Inc.(KMX       )
Arista Networks Inc.(ANET      )
Hologic Inc.(HOLX      )
Teradyne Inc.(TER       )
Hewlett Packard Enterprise Co.(HPE       )
Domino's Pizza Inc.(DPZ       )
Broadridge Financial Solutions Inc.(BR        )
Quest Diagnostics Inc.(DGX       )
Pool Corp.(POOL      )
Amcor plc(AMCR      )
NetApp Inc.(NTAP      )
Tyler Technologies Inc.(TYL       )
KeyCorp(KEY       )
Darden Restaurants Inc.(DRI       )
Duke Realty Corp.(DRE       )
Regions Financial Corp.(RF        )
Bio-Techne Corp.(TECH      )
Healthpeak Properties Inc.(PEAK      )
Western Digital Corp.(WDC       )
Carnival Corp.(CCL       )
WW Grainger Inc.(GWW       )
Hess Corp.(HES       )
Avery Dennison Corp.(AVY       )
Citizens Financial Group Inc.(CFG       )
Take-Two Interactive Software Inc.(TTWO      )
CMS Energy Corp.(CMS       )
Cincinnati Financial Corp.(CINF      )
Teleflex Inc.(TFX       )
Akamai Technologies Inc.(AKAM      )
Royal Caribbean Cruises Ltd.(RCL       )
MarketAxess Holdings Inc.(MKTX      )
AmerisourceBergen Corp. Class A(ABC       )
M&T Bank Corp.(MTB       )
L Brands Inc.(LB        )
Celanese Corp. Class A(CE        )
Halliburton Co.(HAL       )
Viatris Inc.(VTRS      )
Genuine Parts Co.(GPC       )
NVR Inc.(NVR       )
Devon Energy Corp.(DVN       )
Jacobs Engineering Group Inc.(J         )
Seagate Technology Holdings plc(STX       )
MGM Resorts International(MGM       )
Bio-Rad Laboratories Inc. Class A(BIO       )
Consolidated Edison Inc.(ED        )
Raymond James Financial Inc.(RJF       )
IDEX Corp.(IEX       )
Principal Financial Group Inc.(PFG       )
Baker Hughes Co. Class A(BKR       )
ABIOMED Inc.(ABMD      )
Textron Inc.(TXT       )
Boston Properties Inc.(BXP       )
UDR Inc.(UDR       )
Westinghouse Air Brake Technologies Corp.(WAB       )
Conagra Brands Inc.(CAG       )
Kellogg Co.(K         )
AES Corp./VA(AES       )
Omnicom Group Inc.(OMC       )
Evergy Inc.(EVRG      )
Eastman Chemical Co.(EMN       )
Masco Corp.(MAS       )
NortonLifeLock Inc.(NLOK      )
Cardinal Health Inc.(CAH       )
Alliant Energy Corp.(LNT       )
United Airlines Holdings Inc.(UAL       )
JB Hunt Transport Services Inc.(JBHT      )
Las Vegas Sands Corp.(LVS       )
Interpublic Group of Cos. Inc.(IPG       )
LKQ Corp.(LKQ       )
CenterPoint Energy Inc.(CNP       )
Packaging Corp. of America(PKG       )
Incyte Corp.(INCY      )
PulteGroup Inc.(PHM       )
Quanta Services Inc.(PWR       )
Diamondback Energy Inc.(FANG      )
Whirlpool Corp.(WHR       )
Westrock Co.(WRK       )
PTC Inc.(PTC       )
Iron Mountain Inc.(IRM       )
JM Smucker Co.(SJM       )
Fortune Brands Home & Security Inc.(FBHS      )
Dentsply Sirona Inc.(XRAY      )
Cboe Global Markets Inc.(CBOE      )
Advance Auto Parts Inc.(AAP       )
Jack Henry & Associates Inc.(JKHY      )
Kimco Realty Corp.(KIM       )
Leidos Holdings Inc.(LDOS      )
Allegion plc(ALLE      )
Hormel Foods Corp.(HRL       )
Pentair plc(PNR       )
Brown-Forman Corp. Class B(BF.B      )
American Airlines Group Inc.(AAL       )
Citrix Systems Inc.(CTXS      )
Atmos Energy Corp.(ATO       )
Hasbro Inc.(HAS       )
Live Nation Entertainment Inc.(LYV       )
Loews Corp.(L         )
Howmet Aerospace Inc.(HWM       )
Lincoln National Corp.(LNC       )
Lumen Technologies Inc.(LUMN      )
Fox Corp. Class A(FOXA      )
Snap-on Inc.(SNA       )
Universal Health Services Inc. Class B(UHS       )
F5 Networks Inc.(FFIV      )
FMC Corp.(FMC       )
Penn National Gaming Inc.(PENN      )
CH Robinson Worldwide Inc.(CHRW      )
Host Hotels & Resorts Inc.(HST       )
Robert Half International Inc.(RHI       )
Mohawk Industries Inc.(MHK       )
News Corp. Class A(NWSA      )
Tapestry Inc.(TPR       )
NRG Energy Inc.(NRG       )
Mosaic Co.(MOS       )
Regency Centers Corp.(REG       )
DISH Network Corp. Class A(DISH      )
Wynn Resorts Ltd.(WYNN      )
Henry Schein Inc.(HSIC      )
Everest Re Group Ltd.(RE        )
WR Berkley Corp.(WRB       )
Comerica Inc.(CMA       )
Assurant Inc.(AIZ       )
BorgWarner Inc.(BWA       )
AO Smith Corp.(AOS       )
CF Industries Holdings Inc.(CF        )
NiSource Inc.(NI        )
Newell Brands Inc.(NWL       )
Invesco Ltd.(IVZ       )
Norwegian Cruise Line Holdings Ltd.(NCLH      )
Lamb Weston Holdings Inc.(LW        )
Juniper Networks Inc.(JNPR      )
Zions Bancorp NA(ZION      )
DXC Technology Co.(DXC       )
Sealed Air Corp.(SEE       )
Marathon Oil Corp.(MRO       )
DaVita Inc.(DVA       )
Globe Life Inc.(GL        )
Molson Coors Brewing Co. Class B(TAP       )
Western Union Co.(WU        )
Franklin Resources Inc.(BEN       )
Pinnacle West Capital Corp.(PNW       )
Rollins Inc.(ROL       )
Federal Realty Investment Trust(FRT       )
Organon & Co.(OGN       )
Campbell Soup Co.(CPB       )
Discovery Communications Inc.(DISCK     )
Huntington Ingalls Industries Inc.(HII       )
Nielsen Holdings plc(NLSN      )
PVH Corp.(PVH       )
APA Corp.(APA       )
Alaska Air Group Inc.(ALK       )
People's United Financial Inc.(PBCT      )
Vornado Realty Trust(VNO       )
Hanesbrands Inc.(HBI       )
Leggett & Platt Inc.(LEG       )
Cabot Oil & Gas Corp.(COG       )
IPG Photonics Corp.(IPGP      )
Ralph Lauren Corp. Class A(RL        )
Gap Inc.(GPS       )
Perrigo Co. plc(PRGO      )
Unum Group(UNM       )
Fox Corp. Class B(FOX       )
NOV Inc.(NOV       )
Discovery Communications Inc. Class A(DISCA     )
Under Armour Inc. Class A(UAA       )
Under Armour Inc. Class C(UA        )
Berkshire Hathaway Inc. Class A(BRK.A     )
Lennar Corp. Class B(LEN.B     )
News Corp. Class B(NWS       )"""
