list = """
Nestle SA(NESN      )
ASML Holding NV(ASML      )
Roche Holding AG(ROG       )
Novartis AG(NOVN      )
LVMH Moet Hennessy Louis Vuitton SE(MC        )
AstraZeneca plc(AZN       )
SAP SE(SAP       )
Novo Nordisk A/S Class B(NOVO B    )
Siemens AG(SIE       )
Sanofi(SAN       )
Diageo plc(DGE       )
HSBC Holdings plc(HSBA      )
TOTAL SA(TTE       )
GlaxoSmithKline plc(GSK       )
Allianz SE(ALV       )
Schneider Electric SE(SU        )
Adyen NV(ADYEN     )
British American Tobacco plc(BATS      )
BP plc(BP.       )
Rio Tinto plc(RIO       )
L'Oreal SA Loyalty Line( )
Unilever plc(ULVR      )
Prosus NV(PRX       )
Airbus SE(AIR       )
Royal Dutch Shell plc Class B(RDSB      )
Iberdrola SA(IBE       )
Daimler AG(DAI       )
BASF SE(BAS       )
Enel SPA(ENEL      )
Royal Dutch Shell plc Class A(RDSA      )
Deutsche Post AG(DPW       )
Deutsche Telekom AG(DTE       )
BNP Paribas SA(BNP       )
adidas AG(ADS       )
Unilever plc(UNA       )
Zurich Insurance Group AG(ZURN      )
BHP Group plc(BHP       )
Banco Santander SA(SAN       )
ABB Ltd.(ABBN      )
Lonza Group AG(LONN      )
Kering SA(KER       )
EssilorLuxottica SA(EL        )
Air Liquide SA( )
Cie Financiere Richemont SA(CFR       )
Infineon Technologies AG(IFX       )
UBS Group AG(UBSG      )
Bayer AG(BAYN      )
Prudential plc(PRU       )
Glencore plc(GLEN      )
AXA SA(CS        )
ING Groep NV(INGA      )
Vinci SA(DG        )
Anglo American plc(AAL       )
Anheuser-Busch InBev SA/NV(ABI       )
Sika AG(SIKA      )
DSV PANALPINA A/S(DSV       )
Reckitt Benckiser Group plc(RKT       )
Vodafone Group plc(VOD       )
Intesa Sanpaolo SPA (Registered)(ISP       )
Investor AB Class B(INVE B    )
Givaudan SA(GIVN      )
National Grid plc(NG.       )
Hermes International(RMS       )
Pernod Ricard SA(RI        )
Danone SA(BN        )
Atlas Copco AB Class A(ATCO A    )
Safran SA(SAF       )
Banco Bilbao Vizcaya Argentaria SA(BBVA      )
Volkswagen AG Preference Shares(VOW3      )
Barclays plc(BARC      )
Lloyds Banking Group plc(LLOY      )
Koninklijke Philips NV(PHIA      )
Cellnex Telecom SA(CLNX      )
Muenchener Rueckversicherungs-Gesellschaft AG in Muenchen(MUV2      )
Vestas Wind Systems A/S(VWS       )
Experian plc(EXPN      )
London Stock Exchange Group plc(LSEG      )
Partners Group Holding AG(PGHN      )
Vonovia SE(VNA       )
Dassault Systemes SE(DSY       )
Alcon Inc.(ALC       )
Compass Group plc(CPG       )
Industria de Diseno Textil SA(ITX       )
Telefonaktiebolaget LM Ericsson Class B(ERIC B    )
Koninklijke DSM NV(DSM       )
Capgemini SE(CAP       )
Ashtead Group plc(AHT       )
L'Oreal SA(OR        )
Volvo AB Class B(VOLV B    )
Cie de Saint-Gobain(SGO       )
Nokia Oyj(NOKIA     )
Koninklijke Ahold Delhaize NV(AD        )
Kone Oyj Class B(KNEBV     )
Ferguson plc(FERG      )
Flutter Entertainment plc(FLTR      )
Deutsche Boerse AG(DB1       )
Nordea Bank Abp(NDA SE    )
Eni SPA(ENI       )
Hexagon AB Class B(HEXA B    )
Bayerische Motoren Werke AG(BMW       )
Merck KGaA(MRK       )
Legrand SA(LR        )
Wolters Kluwer NV(WKL       )
Orsted A/S(ORSTED    )
Geberit AG(GEBN      )
Assa Abloy AB Class B(ASSA B    )
RELX plc(REL       )
E.ON SE(EOAN      )
Vivendi SA(VIV       )
Cie Generale des Etablissements Michelin SCA(ML        )
STMicroelectronics NV(STM       )
Genmab A/S(GMAB      )
Sandvik AB(SAND      )
Delivery Hero SE(DHER      )
RELX plc(REN       )
UniCredit SPA(UCG       )
Tesco plc(TSCO      )
Swiss Re AG(SREN      )
Ferrari NV(RACE      )
Assicurazioni Generali SPA(G         )
Sampo Oyj Class A(SAMPO     )
Heineken NV(HEIA      )
Amadeus IT Group SA(AMS       )
Evolution Gaming Group AB(EVO       )
Teleperformance(TEP       )
Air Liquide SA(AI        )
Credit Suisse Group AG(CSGN      )
Neste Oyj(NESTE     )
Deutsche Bank AG(DBK       )
BAE Systems plc(BA.       )
Telefonica SA(TEF       )
CRH plc(CRG       )
Stellantis NV(STLA      )
RWE AG(RWE       )
Societe Generale SA(GLE       )
Zalando SE(ZAL       )
SSE plc(SSE       )
ArcelorMittal SA(MT        )
Coloplast A/S Class B(COLO B    )
KBC Group NV(KBC       )
Akzo Nobel NV(AKZA      )
Kerry Group plc Class A(KRZ       )
Legal & General Group plc(LGEN      )
Aviva plc(AV.       )
Orange SA(ORA       )
UPM-Kymmene Oyj(UPM       )
Worldline SA/France(WLN       )
DNB ASA(DNB       )
Atlas Copco AB Class B(ATCO B    )
Deutsche Wohnen SE(DWNI      )
Segro plc(SGRO      )
Fresenius SE & Co. KGaA(FRE       )
Sonova Holding AG(SOON      )
BT Group plc(BT.A      )
Equinor ASA(EQNR      )
Imperial Brands plc(IMB       )
Essity AB Class B(ESSITY B  )
Skandinaviska Enskilda Banken AB Class A(SEB A     )
Straumann Holding AG(STMN      )
Swedbank AB Class A(SWED A    )
Siemens Healthineers AG(SHL       )
ASM International NV(ASM       )
SGS SA(SGSN      )
Kuehne + Nagel International AG(KNIN      )
Symrise AG Class A(SY1       )
LafargeHolcim Ltd.(HOLN      )
Henkel AG & Co. KGaA Preference Shares(HEN3      )
Veolia Environnement SA(VIE       )
Hennes & Mauritz AB Class B(HM B      )
3i Group plc(III       )
Kingspan Group plc(KRX       )
Eurofins Scientific SE(ERF       )
Carlsberg A/S Class B(CARL B    )
Argenx SE(1AE       )
Svenska Handelsbanken AB Class A(SHB A     )
Croda International plc(CRDA      )
CRH plc(CRH       )
Credit Agricole SA(ACA       )
Smith & Nephew plc(SN.       )
Nibe Industrier AB Class B(NIBE B    )
Swiss Life Holding AG(SLHN      )
Sartorius AG Preference Shares(SRT3      )
Engie SA( )
Spirax-Sarco Engineering plc(SPX       )
CNH Industrial NV(CNHI      )
AP Moller - Maersk A/S Class B(MAERSK B  )
Novozymes A/S(NZYM B    )
WPP plc(WPP       )
Standard Chartered plc(STAN      )
HelloFresh SE(HFG       )
Stellantis NV(STLA      )
Halma plc(HLMA      )
Fresenius Medical Care AG & Co. KGaA(FME       )
Brenntag AG(BNR       )
Porsche Automobil Holding SE Preference Shares(PAH3      )
NN Group NV(NN        )
EDP - Energias de Portugal SA(EDP       )
GVC Holdings plc(ENT       )
Repsol SA(REP       )
Royal Bank of Scotland Group plc(NWG       )
Logitech International SA(LOGN      )
Swisscom AG(SCMN      )
Smurfit Kappa Group plc(SKG       )
Rentokil Initial plc(RTO       )
Julius Baer Group Ltd.(BAER      )
Publicis Groupe SA(PUB       )
Sartorius Stedim Biotech(DIM       )
Continental AG(CON       )
Swedish Match AB(SWMA      )
Epiroc AB Class A(EPI A     )
Edenred(EDEN      )
Just Eat Takeaway.com NV(JET       )
UCB SA(UCB       )
Ferrovial SA(FER       )
Next plc(NXT       )
Moncler SPA(MONC      )
CaixaBank SA(CABK      )
Ocado Group plc(OCDO      )
Umicore SA(UMI       )
Mondi plc(MNDI      )
Snam SPA(SRG       )
Schindler Holding AG(SCHP      )
Fortum Oyj(FORTUM    )
HeidelbergCement AG(HEI       )
Persimmon plc(PSN       )
Alfa Laval AB(ALFA      )
Alstom SA(ALO       )
Chocoladefabriken Lindt & Spruengli AG(LISP      )
MTU Aero Engines AG(MTX       )
Bunzl plc(BNZL      )
Chocoladefabriken Lindt & Spruengli AG(LISN      )
QIAGEN NV(QIA       )
Beiersdorf AG(BEI       )
Groupe Bruxelles Lambert SA(GBLB      )
Puma SE(PUM       )
Unibail-Rodamco-Westfield(URW       )
Rolls-Royce Holdings plc(RR.       )
Intertek Group plc(ITRK      )
St. James's Place plc(STJ       )
AP Moller - Maersk A/S Class A(MAERSK A  )
InterContinental Hotels Group plc(IHG       )
EQT AB(EQT       )
Covestro AG(1COV      )
Pandora A/S(PNDORA    )
Sinch AB(SINCH     )
Carrefour SA(CA        )
LEG Immobilien AG(LEG       )
Mowi ASA(MOWI      )
Erste Group Bank AG(EBS       )
Aena SME SA(AENA      )
Stora Enso Oyj(STERV     )
FinecoBank Banca Fineco SPA(FBK       )
IMCD NV(IMCD      )
LafargeHolcim Ltd.(HOLN      )
Kesko Oyj Class B(KESKOB    )
Royal Dutch Shell plc Class A(RDSA      )
Terna Rete Elettrica Nazionale SPA(TRN       )
Telia Co. AB(TELIA     )
Sage Group plc(SGE       )
Danske Bank A/S(DANSKE    )
Telenor ASA(TEL       )
Hannover Rueck SE(HNR1      )
Informa plc(INF       )
Svenska Cellulosa AB SCA Class B(SCA B     )
Siemens Energy AG(ENR       )
Volkswagen AG(VOW       )
VAT Group AG(VACN      )
Koninklijke KPN NV(KPN       )
Nordea Bank Abp(NDA FI    )
Admiral Group plc(ADM       )
Thales SA(HO        )
Barratt Developments plc(BDEV      )
Burberry Group plc(BRBY      )
Skanska AB Class B(SKA B     )
SIG Combibloc Group AG(SIGN      )
Kingfisher plc(KGF       )
Melrose Industries plc(MRO       )
United Utilities Group plc(UU.       )
Prysmian SPA(PRY       )
Heineken Holding NV(HEIO      )
GN Store Nord A/S(GN        )
SKF AB(SKF B     )
Temenos AG(TEMN      )
Boliden AB(BOL       )
Associated British Foods plc(ABF       )
Chr Hansen Holding A/S(CHR       )
Kinnevik AB(KINV B    )
Euronext NV(ENX       )
Bureau Veritas SA(BVI       )
Powszechna Kasa Oszczednosci Bank Polski SA(PKO       )
Investor AB Class A(INVE A    )
Nexi SPA(NEXI      )
Aroundtown SA(AT1       )
Indutrade AB(INDT      )
Norsk Hydro ASA(NHY       )
Atlantia SPA(ATL       )
Getinge AB(GETI B    )
Severn Trent plc(SVT       )
Elisa Oyj(ELISA     )
Barry Callebaut AG(BARN      )
Solvay SA Class A(SOLB      )
Taylor Wimpey plc(TW.       )
Ageas(AGS       )
Bouygues SA(EN        )
Meggitt plc(MGGT      )
Arkema SA(AKE       )
Whitbread plc(WTB       )
Wm Morrison Supermarkets plc(MRW       )
Suez(SEV       )
EXOR NV(EXO       )
Aegon NV(AGN       )
Mediobanca Banca di Credito Finanziario SPA(MB        )
Red Electrica Corp. SA(REE       )
Yara International ASA(YAR       )
Adecco Group AG(ADEN      )
Henkel AG & Co. KGaA(HEN       )
Intermediate Capital Group plc(ICP       )
DCC plc(DCC       )
KION Group AG(KGX       )
Rightmove plc(RMV       )
Roche Holding AG (Bearer)(RO        )
Auto Trader Group plc(AUTO      )
Swatch Group AG (Bearer)(UHR       )
Grifols SA(GRF       )
Randstad NV(RAND      )
Carl Zeiss Meditec AG(AFX       )
Swiss Prime Site AG(SPSN      )
Gecina SA(GFC       )
Tele2 AB(TEL2 B    )
Smiths Group plc(SMIN      )
Pearson plc(PSON      )
Standard Life Aberdeen plc(ABDN      )
Knorr-Bremse AG(KBX       )
Castellum AB(CAST      )
Hargreaves Lansdown plc(HL.       )
OMV AG(OMV       )
Industrivarden AB Class A(INDU A    )
Eiffage SA(FGR       )
DS Smith plc(SMDS      )
EMS-Chemie Holding AG(EMSN      )
Johnson Matthey plc(JMAT      )
GEA Group AG(G1A       )
Naturgy Energy Group SA(NTGY      )
Tryg A/S(TRYG      )
Endesa SA(ELE       )
Dechra Pharmaceuticals plc(DPH       )
Berkeley Group Holdings plc(BKG       )
Engie SA(ENGI      )
Howden Joinery Group plc(HWDN      )
M&G plc(MNG       )
Vifor Pharma AG(VIFN      )
Tecan Group AG(TECN      )
Getlink SE(GET       )
Fastighets AB Balder Class B(BALD B    )
Evotec SE(EVT       )
Tomra Systems ASA(TOM       )
Verbund AG(VER       )
Coca-Cola HBC AG(CCH       )
Allegro.eu SA(ALE       )
Baloise Holding AG(BALN      )
Land Securities Group plc(LAND      )
Scout24 AG(G24       )
Polymetal International plc(POLY      )
Signify NV(LIGHT     )
Davide Campari-Milano NV(CPR       )
Antofagasta plc(ANTO      )
Wartsila OYJ Abp(WRT1V     )
Electrocomponents plc(ECM       )
B&M European Value Retail SA(BME       )
J Sainsbury plc(SBRY      )
Renault SA(RNO       )
Orkla ASA(ORK       )
Epiroc AB Class B(EPI B     )
Valeo SA(FR        )
JD Sports Fashion plc(JD.       )
Lifco AB Class B(LIFCO B   )
AVEVA Group plc(AVV       )
IMI plc(IMI       )
British Land Co. plc(BLND      )
Amplifon SPA(AMP       )
Sofina SA(SOF       )
BE Semiconductor Industries NV(BESI      )
Georg Fischer AG(FI-N      )
Siemens Gamesa Renewable Energy SA(SGRE      )
Warehouses De Pauw CVA(WDP       )
Commerzbank AG(CBK       )
Sagax AB Class B(SAGA B    )
Evonik Industries AG(EVK       )
Outotec Oyj(MOCORP    )
ACS Actividades de Construccion y Servicios SA(ACS       )
Recordati SPA(REC       )
EDP Renovaveis SA(EDPR      )
Rexel SA(RXL       )
KGHM Polska Miedz SA(KGH       )
Accor SA(AC        )
ASR Nederland NV(ASRNL     )
Royal Unibrew A/S(RBREW     )
LANXESS AG(LXS       )
Spectris plc(SXS       )
Royal Mail plc(RMG       )
Weir Group plc(WEIR      )
Poste Italiane SPA(PST       )
Orpea(ORP       )
Aalberts NV(AALB      )
Polski Koncern Naftowy ORLEN SA(PKN       )
Electricite de France SA( )
Ubisoft Entertainment SA(UBI       )
Bellway plc(BWY       )
Future plc(FUTR      )
Demant A/S(DEMANT    )
Schindler Holding AG (Registered)(SCHN      )
Trelleborg AB Class B(TREL B    )
Powszechny Zaklad Ubezpieczen SA(PZU       )
Bechtle AG(BC8       )
Telecom Italia SPA (Registered)(TIT       )
ITV plc(ITV       )
Hikma Pharmaceuticals plc(HIK       )
Husqvarna AB(HUSQ B    )
Bollore SA(BOL       )
Schroders plc(SDR       )
Electrolux AB Class B(ELUX B    )
PSP Swiss Property AG(PSPN      )
Direct Line Insurance Group plc(DLG       )
Lundin Petroleum AB(LUNE      )
Beijer Ref AB(BEIJ B    )
ABN AMRO Bank NV(ABN       )
Thule Group AB(THULE     )
Bank of Ireland Group plc(BIRG      )
Interpump Group SPA(IP        )
Dialog Semiconductor plc(DLG       )
Enagas SA(ENG       )
Industrivarden AB(INDU C    )
Travis Perkins plc(TPK       )
Tritax Big Box REIT plc(BBOX      )
Ambu A/S Class B(AMBU B    )
SimCorp A/S(SIM       )
Amundi SA(AMUN      )
Phoenix Group Holdings plc(PHNX      )
Valmet Oyj(VALMT     )
Genus plc(GNS       )
UNITE Group plc(UTG       )
Nemetschek SE(NEM       )
Galp Energia SGPS SA(GALP      )
Aedifica SA(AED       )
TeamViewer AG(TMV       )
Derwent London plc(DLN       )
BioMerieux(BIM       )
Games Workshop Group plc(GAW       )
thyssenkrupp AG(TKA       )
voestalpine AG(VOE       )
THG plc(THG       )
Nokian Renkaat Oyj(TYRES     )
Jeronimo Martins SGPS SA(JMT       )
Securitas AB Class B(SECU B    )
DiaSorin SPA(DIA       )
Diploma plc(DPLM      )
Investment AB Latour Class B(LATO B    )
Dometic Group AB(DOM       )
SOITEC(SOI       )
Nordic Semiconductor ASA(NOD       )
Samhallsbyggnadsbolaget i Norden AB(SBB B     )
ams AG(AMS       )
Inchcape plc(INCH      )
ConvaTec Group plc(CTEC      )
Banco BPM SPA(BAMI      )
Atos SE(ATO       )
Huhtamaki Oyj(HUH1V     )
Holmen AB(HOLM B    )
Pennon Group plc(PNN       )
Remy Cointreau SA(RCO       )
Marks & Spencer Group plc(MKS       )
Fabege AB(FABG      )
Clariant AG(CLN       )
SCOR SE(SCR       )
Covivio(COV       )
Belimo Holding AG(BEAN      )
Schibsted ASA Class B(SCHB      )
Adevinta ASA(ADE       )
Tenaris SA(TEN       )
Kojamo Oyj(KOJAMO    )
Faurecia SE(EO        )
United Internet AG(UTDI      )
Evraz plc(EVR       )
Avanza Bank Holding AB(AZA       )
Alten SA(ATE       )
L E Lundbergforetagen AB Class B(LUND B    )
Cofinimmo SA(COFB      )
IG Group Holdings plc(IGG       )
Bayerische Motoren Werke AG Preference Shares(BMW3      )
Reply SPA(REY       )
Tate & Lyle plc(TATE      )
Klepierre SA(LI        )
Avast plc(AVST      )
La Francaise des Jeux SAEM(FDJ       )
Volvo AB Class A(VOLV A    )
Bakkafrost P/F(BAKKA     )
Elekta AB Class B(EKTA B    )
Wienerberger AG(WIE       )
Elia System Operator SA/NV(ELI       )
Bank Polska Kasa Opieki SA(PEO       )
Nordic Entertainment Group AB Class B(NENT B    )
LPP SA(LPP       )
Fluidra SA(FDR       )
TAG Immobilien AG(TEG       )
Sodexo SA( )
Rheinmetall AG(RHM       )
ISS A/S(ISS       )
Netcompany Group A/S(NETC      )
Man Group PLC/Jersey(EMG       )
Hiscox Ltd.(HSX       )
Orion Oyj Class B(ORNBV     )
Grafton Group plc(GFTU      )
Centrica plc(CNA       )
Greggs plc(GRG       )
Storebrand ASA(STB       )
Infrastrutture Wireless Italiane SPA(INW       )
Bachem Holding AG(BANB      )
Ackermans & van Haaren NV(ACKB      )
AAK AB(AAK       )
Dino Polska SA(DNP       )
ANDRITZ AG(ANDR      )
Bankinter SA(BKT       )
Wendel SA(MF        )
Helvetia Holding AG(HELN      )
Banco de Sabadell SA(SAB       )
AddTech AB(ADDT B    )
Rotork plc(ROR       )
Countryside Properties plc(CSP       )
InPost SA(INPST     )
Vitrolife AB(VITR      )
Merlin Properties Socimi SA(MRL       )
Swedish Orphan Biovitrum AB(SOBI      )
BillerudKorsnas AB(BILL      )
Siegfried Holding AG(SFZN      )
Rational AG(RAA       )
Gjensidige Forsikring ASA(GJF       )
Schibsted ASA Class A(SCHA      )
Galenica AG(GALE      )
ICA Gruppen AB(ICA       )
CTS Eventim AG & Co. KGaA(EVD       )
Fuchs Petrolub SE Preference Shares(FPE3      )
Entra ASA(ENTRA     )
Acciona SA(ANA       )
alstria office REIT-AG(AOX       )
Quilter plc(QLT       )
Rubis SCA(RUI       )
Bovis Homes Group plc(VTY       )
Virgin Money UK plc(VMUK      )
Arcadis NV(ARCAD     )
Softcat plc(SCT       )
D'ieteren SA/NV(DIE       )
Britvic plc(BVIC      )
Glanbia plc(GL9       )
HomeServe plc(HSV       )
QT Group Oyj(QTCOM     )
Inmobiliaria Colonial Socimi SA(COL       )
Uniper SE(UN01      )
Salmar ASA(SALM      )
Sweco AB Class B(SWEC B    )
Ringkjoebing Landbobank A/S(RILBA     )
Ipsen SA(IPN       )
BAWAG Group AG(BG        )
Azimut Holding SPA(AZM       )
A2A SPA(A2A       )
Hays plc(HAS       )
Gerresheimer AG(GXI       )
Bucher Industries AG(BUCN      )
Big Yellow Group plc(BYG       )
Aeroports de Paris(ADP       )
Iliad SA(ILD       )
Rockwool International A/S Class B(ROCK B    )
Konecranes Oyj Class A(KCR       )
AF POYRY AB(AFRY      )
Hera SPA(HER       )
Leonardo SPA(LDO       )
Italgas SPA(IG        )
SEB SA Loyalty Line( )
ALK-Abello A/S(ALK B     )
SSAB AB Class B(SSAB B    )
Wihlborgs Fastigheter AB(WIHL      )
Zur Rose Group AG(ROSE      )
Pets at Home Group plc(PETS      )
Safestore Holdings plc(SAFE      )
Watches of Switzerland Group plc(WOSG      )
Befesa SA(BFSA      )
Hella GmbH & Co. KGaA(HLE       )
Close Brothers Group plc(CBG       )
Beazley plc(BEZ       )
Bravida Holding AB(BRAV      )
Lagardere SCA(MMB       )
Hexpol AB(HPOL B    )
Freenet AG(FNTN      )
Corbion NV(CRBN      )
LondonMetric Property plc(LMP       )
Flughafen Zurich AG(FHZN      )
SES SA Class A(SESG      )
Raiffeisen Bank International AG(RBI       )
AIXTRON SE(AIXA      )
Victrex plc(VCT       )
Bavarian Nordic A/S(BAVA      )
SPIE SA(SPIE      )
Ultra Electronics Holdings plc(ULE       )
TechnipFMC plc(FTI       )
Deutsche Lufthansa AG(LHA       )
Allreal Holding AG(ALLN      )
ProSiebenSat.1 Media SE(PSM       )
Aurubis AG(NDA       )
Primary Health Properties plc(PHP       )
zooplus AG(ZO1       )
Sopra Steria Group(SOP       )
Nexans SA(NEX       )
JDE Peet's NV(JDEP      )
Siltronic AG(WAF1      )
Dufry AG(DUFN      )
SSP Group plc(SSPG      )
Sodexo SA(SW        )
IWG plc(IWG       )
CD Projekt SA(CDR       )
Banca Mediolanum SPA(BMED      )
Computacenter plc(CCC       )
Grainger plc(GRI       )
Auto1 Group SE(AG1       )
De' Longhi SPA(DLG       )
Arjo AB(ARJO B    )
SBM Offshore NV(SBMO      )
Comet Holding AG(COTN      )
Unipol Gruppo SPA(UNI       )
Polskie Gornictwo Naftowe i Gazownictwo SA(PGN       )
Carnival plc(CCL       )
Pirelli & C SPA(PIRC      )
Aker BP ASA(AKRBP     )
British American Tobacco plc ADR(BTI       )
HUGO BOSS AG(BOSS      )
Kungsleden AB(KLED      )
Nordnet AB publ(SAVE      )
Galapagos NV(GLPG      )
Softwareone Holding AG(SWON      )
Assura plc(AGR       )
Cranswick plc(CWK       )
Colruyt SA(COLR      )
DKSH Holding AG(DKSH      )
Koninklijke Vopak NV(VPK       )
Wallenstam AB(WALL B    )
WH Smith plc(SMWH      )
Investec plc(INVP      )
Viscofan SA(VIS       )
APERAM SA(APAM      )
Saab AB Class B(SAAB B    )
Proximus SADP(PROX      )
Axfood AB(AXFO      )
Hypoport AG(HYQ       )
ICADE(ICAD      )
Pagegroup plc(PAGE      )
John Laing Group plc(JLG       )
Wacker Chemie AG(WCH       )
K+S AG(SDF       )
Great Portland Estates plc(GPOR      )
JM AB(JM        )
Nyfosa AB(NYF       )
Idorsia Ltd.(IDIA      )
Cargotec Oyj Class B(CGCBV     )
Balfour Beatty plc(BBY       )
Sectra AB Class B(SECT B    )
Sulzer AG(SUN       )
Daetwyler Holding AG(DAE       )
QinetiQ Group plc(QQ.       )
Domino's Pizza Group plc(DOM       )
Buzzi Unicem SPA(BZU       )
OSB Group plc(OSB       )
Eurazeo Loyalty Line 2023( )
Borregaard ASA(BRG       )
Elis SA(ELIS      )
Vontobel Holding AG(VONN      )
Jungheinrich AG Preference Shares(JUN3      )
CNP Assurances(CNP       )
Cyfrowy Polsat SA(CPS       )
Acerinox SA(ACX       )
Dassault Aviation SA(AM        )
TKH Group NV(TWEKA     )
Bure Equity AB(BURE      )
Boskalis Westminster(BOKA      )
Renishaw plc(RSW       )
Wizz Air Holdings plc(WIZZ      )
Banca Generali SPA(BGN       )
Instalco AB(INSTAL    )
Savills plc(SVS       )
Ashmore Group plc(ASHM      )
Korian SA(KORI      )
Shaftesbury plc(SHB       )
Swatch Group AG (Registered)(UHRN      )
Software AG(SOW       )
Network International Holdings plc(NETW      )
PostNL NV(PNL       )
Polypipe Group plc(GEN       )
Bodycote plc(BOY       )
TietoEVRY Oyj(TIETO     )
Grand City Properties SA(GYC       )
Jyske Bank A/S(JYSK      )
SFS Group AG(SFSN      )
Scatec Solar ASA(SCATC     )
easyJet plc(EZJ       )
Spirent Communications plc(SPT       )
Synthomer plc(SYNT      )
Duerr AG(DUE       )
Talanx AG(TLX       )
International Consolidated Airlines Group SA (London Shares)(IAG       )
CANCOM SE(COK       )
SpareBank 1 SR-Bank ASA(SRBNK     )
Inficon Holding AG(IFCN      )
Banque Cantonale Vaudoise(BCVN      )
OCI NV(OCI       )
Santander Bank Polska SA(SPL       )
MIPS AB(MIPS      )
Peab AB Class B(PEAB B    )
Takeaway.com NV(JETl      )
IMMOFINANZ AG(IIA       )
ADO Properties SA(ADJ       )
Interroll Holding AG(INRN      )
Forbo Holding AG(FORN      )
RTL Group SA(RRTL      )
Loomis AB Class B(LOOMIS    )
CompuGroup Medical SE & Co. KgaA(COP       )
Mobimo Holding AG(MOBN      )
Melexis NV(MELE      )
Dr. Martens plc(DOCS      )
AIB Group plc(A5G       )
Intrum AB(INTRUM    )
BPER Banca(BPE       )
Fraport AG Frankfurt Airport Services Worldwide(FRA       )
Trainline plc(TRN       )
Varta AG(VAR1      )
John Wood Group plc(WG.       )
Nexity SA(NXI       )
Drax Group plc(DRX       )
Leroy Seafood Group ASA(LSG       )
Nel ASA(NEL       )
Ascential plc(ASCL      )
dormakaba Holding AG(DOKA      )
Emmi AG(EMMN      )
Cerved Group SPA(CERV      )
Redrow plc(RDW       )
Topdanmark A/S(TOP       )
TP ICAP Group plc(TCAP      )
Serco Group plc(SRP       )
Fresnillo plc(FRES      )
OC Oerlikon Corp. AG(OERL      )
Marshalls plc(MSLH      )
Cembra Money Bank AG(CMBN      )
Eutelsat Communications SA(ETL       )
Kongsberg Gruppen ASA(KOG       )
Freni Brembo SPA(BRE       )
Mycronic AB(MYCR      )
Gaztransport Et Technigaz SA(GTT       )
Mapfre SA(MAP       )
BKW AG(BKW       )
Sixt SE(SIX2      )
Stadler Rail AG(SRAIL     )
IntegraFin Holdings plc(IHP       )
Outokumpu Oyj(OUT1V     )
Basic-Fit NV(BFIT      )
Stroeer SE & Co. KGaA(SAX       )
Gamesys Group plc(GYS       )
Lancashire Holdings Ltd.(LRE       )
Plus500 Ltd.(PLUS      )
Nolato AB Class B(NOLA B    )
Grupo Catalana Occidente SA(GCO       )
Hill & Smith Holdings plc(HILS      )
Hammerson plc(HMSO      )
JCDecaux SA(DEC       )
Banca Popolare di Sondrio SCPA(BPSO      )
Hufvudstaden AB Class A(HUFV A    )
Brunello Cucinelli SPA(BC        )
Dunelm Group plc(DNLM      )
Iren SPA(IRE       )
Stabilus SA(STM       )
Verallia SA(VRLA      )
Conzzeta AG(BYS       )
Indivior plc(INDV      )
Sanne Group plc(SNN       )
NKT A/S(NKT       )
Montea C.V.A(MONT      )
Lindab International AB(LIAB      )
Nordex SE(NDX1      )
IPSOS(IPS       )
Paragon Banking Group plc(PAG       )
PGE Polska Grupa Energetyczna SA(PGE       )
Dixons Carphone plc(DC.       )
MorphoSys AG(MOR       )
Oxford Instruments plc(OXIG      )
SpareBank 1 SMN(MING      )
National Express Group plc(NEX       )
Telefonica Deutschland Holding AG(O2D       )
Landis+Gyr Group AG(LAND      )
Eurazeo SE(RF        )
Virbac SA(VIRP      )
Fielmann AG(FIE       )
Biotage AB(BIOT      )
Metsa Board Oyj(METSB     )
Aston Martin Lagonda Global Holdings plc(AML       )
Telecom Italia SPA (Bearer)(TITR      )
Norwegian Finans Holding ASA(BANO      )
Jenoptik AG(JEN       )
Imerys SA(NK        )
Mayr Melnhof Karton AG(MMK       )
FLSmidth & Co. A/S(FLS       )
Lenzing AG(LNZ       )
Moneysupermarket.com Group plc(MONY      )
Subsea 7 SA(SUBC      )
VGP NV(VGP       )
Electrolux Professional AB Class B(EPRO B    )
Uponor Oyj(UPONOR    )
H Lundbeck A/S(LUN       )
CA Immobilien Anlagen AG(CAI       )
Aker ASA(AKER      )
Revenio Group Oyj(REG1V     )
KBC Ancora(KBCA      )
Telenet Group Holding NV(TNET      )
IP Group plc(IPO       )
Capital & Counties Properties plc(CAPC      )
Encavis AG(ECV       )
Sydbank A/S(SYDB      )
Frasers Group plc(FRAS      )
AJ Bell plc(AJB       )
Trigano SA(TRI       )
Dfds A/S(DFDS      )
Atea ASA(ATEA      )
NCC AB Class B(NCC B     )
BICO Group AB Class B(BICO      )
Medicover AB Class B(MCOV B    )
METRO AG(B4B       )
TUI AG(TUIl      )
Barco NV(BAR       )
Cie Plastic Omnium SA(POM       )
Playtech plc(PTEC      )
Societe BIC SA(BB        )
Workspace Group plc(WKP       )
Mediclinic International plc(MDC       )
Euronav NV(EURN      )
Norma Group SE(NOEJ      )
Banca Farmafactoring SPA(BFF       )
Swissquote Group Holding SA(SQN       )
Catena AB(CATE      )
ERG SPA(ERG       )
Valiant Holding AG(VATN      )
Bekaert SA(BEKB      )
Micro Focus International plc(MCRO      )
Sirius Real Estate Ltd.(SRE       )
GrandVision NV(GVNV      )
Neles Oyj(NELES     )
Kardex AG(KARN      )
Brewin Dolphin Holdings plc(BRW       )
Vesuvius plc(VSVS      )
Technip Energies NV(TE        )
Dermapharm Holding SE(DMP       )
Aareal Bank AG(ARL       )
Casino Guichard Perrachon SA(CO        )
Rathbone Brothers plc(RAT       )
Bilia AB(BILI A    )
Ebro Foods SA(EBRO      )
Jupiter Fund Management plc(JUP       )
Chemometec A/S(CHEMM     )
HOCHTIEF AG(HOT       )
Huber + Suhner AG(HUBN      )
Oesterreichische Post AG(POST      )
Rhi Magnesita NV(RHIM      )
Grupa Lotos SA(LTS       )
Morgan Advanced Materials plc(MGAM      )
Ferrexpo plc(FXPO      )
Firstgroup plc(FGP       )
Kemira Oyj(KEMIRA    )
Krones AG(KRN       )
Coats Group plc(COA       )
Schweiter Technologies AG(SWTQ      )
Northgate plc(REDD      )
Shurgard Self Storage SA(SHUR      )
Kainos Group plc(KNOS      )
FDM Group Holdings plc(FDM       )
CIE Automotive SA(CIE       )
888 Holdings plc(888       )
Euromoney Institutional Investor plc(ERM       )
DWS Group GmbH & Co. KGaA(DWS       )
Traton SE(8TRA      )
Orange Polska SA(OPL       )
Deutsche Pfandbriefbank AG(PBB       )
Centamin plc(CEY       )
UnipolSai Assicurazioni SPA(US        )
Pandox AB Class B(PNDX B    )
Technogym SPA(TGYM      )
1&1 Drillisch AG(1U1       )
Salzgitter AG(SZG       )
SEB SA(SK        )
Linea Directa Aseguradora SA Cia de Seguros y Reaseguros(LDA       )
TUI AG(TUI1      )
Modern Times Group MTG AB Class B(MTG B     )
Applus Services SA(APPS      )
Veidekke ASA(VEI       )
Salvatore Ferragamo SPA(SFER      )
Metropole Television SA(MMT       )
Crest Nicholson Holdings plc(CRST      )
Bytes Technology Group plc(BYIT      )
Anima Holding SPA(ANIM      )
Pfeiffer Vacuum Technology AG(PFV       )
Schouw & Co. A/S(SCHO      )
Instone Real Estate Group AG(INS       )
Intertrust NV(INTER     )
Autogrill SPA(AGL       )
KRUK SA(KRU       )
Indra Sistemas SA(IDR       )
GVS SPA(GVS       )
Coface SA(COFA      )
Cia de Distribucion Integral Logista Holdings SA(LOG       )
St. Galler Kantonalbank AG(SGKN      )
Sanoma Oyj(SAA1V     )
Air France-KLM(AF        )
Troax Group AB(TROAX     )
Mitie Group plc(MTO       )
Zealand Pharma A/S(ZEAL      )
Suedzucker AG(SZU       )
Aryzta AG(ARYN      )
Sesa SPA(SES       )
S IMMO AG(SPI       )
BHG Group AB(BHG       )
Saipem SPA(SPM       )
Just Group plc(JUST      )
Global Fashion Group SA(GFG       )
Ratos AB(RATO B    )
VZ Holding AG(VZN       )
Scandinavian Tobacco Group A/S(STG       )
Vectura Group plc(VEC       )
Eurocommercial Properties NV(ECMPA     )
mBank SA(MBK       )
Granges AB(GRNG      )
Cairn Energy plc(CNE       )
TGS NOPEC Geophysical Co. ASA(TGS       )
J D Wetherspoon plc(JDW       )
Fagron(FAGR      )
Clarkson plc(CKN       )
Elis SA(0RA8      )
Burckhardt Compression Holding AG(BCHN      )
Boozt AB(BOOZT     )
Ibstock plc(IBST      )
Airtel Africa plc(AAF       )
Chemring Group plc(CHG       )
Vitec Software Group AB(VIT B     )
Shop Apotheke Europe NV(SAE       )
Gimv NV(GIMB      )
Babcock International Group plc(BAB       )
Banco Comercial Portugues SA(BCP       )
Xior Student Housing NV(XIOR      )
Almirall SA(ALM       )
Asseco Poland SA(ACP       )
Deutsche EuroShop AG(DEQ       )
Faurecia SE(EO        )
Laboratorios Farmaceuticos Rovi SA(ROVI      )
Telekom Austria AG Class A(TKA       )
Carel Industries SPA(CRL       )
Provident Financial plc(PFG       )
Fnac Darty SA(FNAC      )
Solaria Energia y Medio Ambiente SA(SLR       )
Restaurant Group plc(RTN       )
Elementis plc(ELM       )
VERBIO Vereinigte BioEnergie AG(VBK       )
STRATEC SE(SBS       )
Pharma Mar SA(PHM       )
Atrium Ljungberg AB(ATRLJ B   )
Tamburi Investment Partners SPA(TIP       )
Faes Farma SA(FAE       )
Zardoya Otis SA(ZOT       )
Deutz AG(DEZ       )
GRENKE AG(GLJ       )
SSAB AB Class A(SSAB A    )
Alfen Beheer BV(ALFEN     )
NCC Group plc(NCC       )
Essentra plc(ESNT      )
LEM Holding SA(LEHN      )
Crayon Group Holding ASA(CRAYN     )
Hilton Food Group plc(HFG       )
Derichebourg SA(DBG       )
REN - Redes Energeticas Nacionais SGPS SA(RENE      )
Austevoll Seafood ASA(AUSS      )
Betsson AB Class B(BETS B    )
Tessenderlo Chemie NV (Voting Shares)(TESB      )
TI Fluid Systems plc Class B(TIFS      )
S&T AG(SANT      )
Ninety One plc(N91       )
Unicaja Banco SA(UNI       )
Neoen SA(NEOEN     )
Vienna Insurance Group AG Wiener Versicherung Gruppe(VIG       )
Enav SPA(ENAV      )
ALD SA(ALD       )
Interparfums SA(ITP       )
Flow Traders(FLOW      )
XP Power Ltd.(XPP       )
Rothschild & Co.(ROTH      )
Television Francaise 1(TFI       )
Elkem ASA(ELK       )
AT&S Austria Technologie & Systemtechnik AG(ATS       )
Capita plc(CPI       )
Fugro NV(FUR       )
ACEA SPA(ACE       )
AMG Advanced Metallurgical Group NV(AMG       )
PATRIZIA AG(PAT       )
Energean plc(ENOG      )
Europcar Mobility Group(EUCAR     )
FUCHS PETROLUB SE(FPE       )
Mitchells & Butlers plc(MAB       )
Gruppo MutuiOnline SPA(MOL       )
UNIQA Insurance Group AG(UQA       )
Accell Group NV(ACCEL     )
Sonae SGPS SA(SON       )
Draegerwerk AG & Co. KGaA Preference Shares(DRW3      )
Zehnder Group AG(ZEHN      )
Senior plc(SNR       )
Maisons du Monde SA(MDM       )
Bilfinger SE(GBF       )
Alior Bank SA(ALR       )
Hibernia REIT plc(HBRN      )
Keller Group plc(KLR       )
Bank Millennium SA(MIL       )
Greencore Group plc(GNC       )
Dalata Hotel Group plc(DHG       )
Halfords Group plc(HFD       )
EVN AG(EVN       )
Platzer Fastigheter Holding AB Class B(PLAZ B    )
Eckert & Ziegler Strahlen- und Medizintechnik AG(EUZ       )
Societa Cattolica di Assicurazioni SC(CASS      )
Quadient(QDT       )
Sacyr SA(SCYR      )
bpost SA(BPOST     )
Corem Property Group AB Class B(CORE B    )
Nilfisk Holding A/S(NLFSK     )
Munters Group AB(MTRS      )
YIT Oyj(YIT       )
Nobia AB(NOBI      )
Kloeckner & Co. SE(KCO       )
Navigator Co. SA(NVG       )
Sligro Food Group NV(SLIGR     )
Mediaset Espana Comunicacion SA(TL5       )
VNV Global AB(VNV       )
DIC Asset AG(DIC       )
Komax Holding AG(KOMN      )
Spar Nord Bank A/S(SPNO      )
Arbonia AG(ARBN      )
NOS SGPS SA(NOS       )
Sixt SE Preference Shares(SIX3      )
CCC SA(CCC       )
Befimmo SA(BEFB      )
Tauron Polska Energia SA(TPE       )
Falck Renewables SPA(FKR       )
Terveystalo Oyj(TTALO     )
Hornbach Holding AG & Co. KGaA(HBH       )
Zeal Network SE(TIMA      )
Solutions 30 SE(S30       )
KWS Saat SE & Co. KGaA(KWS       )
Ontex Group NV(ONTEX     )
ALSO Holding AG(ALSN      )
Spire Healthcare Group plc(SPI       )
Medacta Group SA(MOVE      )
Cineworld Group plc(CINE      )
Electricite de France SA(EDF       )
Cairn Homes plc(C5H       )
AO World plc(AO.       )
Bonava AB(BONAV B   )
Albioma SA Loyalty Line( )
Sbanken ASA(SBANK     )
Bank of Georgia Group plc(BGEO      )
Telecom Plus plc(TEP       )
Mediaset SPA(MS        )
Dios Fastigheter AB(DIOS      )
Tullow Oil plc(TLW       )
New Work SE(NWO       )
Vetropack Holding AG(VETN      )
Tinexta SPA(TNXT      )
AGFA-Gevaert NV(AGFB      )
Petropavlovsk plc(POG       )
Salini Impregilo SPA(WBD       )
CECONOMY AG(CEC       )
C&C Group plc(GCC       )
Bossard Holding AG(BOSN      )
Samhallsbyggnadsbolaget i Norden AB(SBB D     )
Drilling Co. of 1972 A/S(DRLCO     )
Atoss Software AG(AOF       )
MARR SPA(MARR      )
SkiStar AB(SKIS B    )
Wickes Group plc(WIX       )
Construcciones y Auxiliar de Ferrocarriles SA(CAF       )
NSI NV(NSI       )
Equiniti Group plc(EQN       )
Irish Continental Group plc(IR5B      )
UK Commercial Property REIT Ltd.(UKCM      )
Concentric AB(COIC      )
Voltalia SA(VLTSA     )
Valora Holding AG(VALN      )
CTT-Correios de Portugal SA(CTT       )
Prosegur Cia de Seguridad SA(PSG       )
Kernel Holding SA(KER       )
SOL SPA(SOL       )
SAS AB(SAS       )
Koninklijke BAM Groep NV(BAMNB     )
Wacker Neuson SE(WAC       )
Indus Holding AG(INH       )
Secunet Security Networks AG(YSN       )
Retail Estates NV(RET       )
Moonpig Group plc(MOON      )
Mekonomen AB(MEKO      )
Picton Property Income Ltd.(PCTN      )
Robertet SA(RBT       )
Marston's plc(MARS      )
Mercialys SA(MERY      )
Cie d'Entreprises CFE(CFEB      )
PureTech Health plc(PRTC      )
Melia Hotels International SA(MEL       )
BMO Commercial Property Trust(BCPT      )
Golden Ocean Group Ltd.(GOGL      )
Avon Rubber plc(AVON      )
Danieli & C Officine Meccaniche SPA(DANR      )
TBC Bank Group plc(TBCG      )
Vicat SA(VCT       )
Gestamp Automocion SA(GEST      )
Bonheur ASA(BONHR     )
Eramet(ERA       )
Elior Group SA(ELIOR     )
Washtec AG(WSU       )
Resurs Holding AB(RESURS    )
Strabag SE(STR       )
Rieter Holding AG(RIEN      )
Bobst Group SA(BOBNN     )
Leonteq AG(LEON      )
Cloetta AB Class B(CLA B     )
Intershop Holding AG(ISN       )
doValue SPA(DOV       )
Helical plc(HLCL      )
Kinepolis Group NV(KIN       )
FFP(PEUG      )
Neinor Homes SA(HOME      )
Akka Technologies(AKA       )
Hochschild Mining plc(HOC       )
TietoEVRY Oyj(TIETO     )
Schaeffler AG Preference Shares(SHA       )
D/S Norden A/S(DNORD     )
Hansa Biopharma AB(HNSA      )
CMC Markets plc(CMCX      )
Frontline Ltd./Bermuda(FRO       )
INVISIO AB(IVSO      )
AG Barr plc(BAG       )
COSMO Pharmaceuticals NV(COPN      )
PZ Cussons plc(PZC       )
Meyer Burger Technology AG(MBTN      )
Citycon Oyj(CTY1S     )
Deutsche Beteiligungs AG(DBAN      )
Zignago Vetro SPA(ZV        )
HMS Networks AB(HMS       )
Wereldhave NV(WHA       )
Aedas Homes SAU(AEDAS     )
Kinnevik AB(KINV A    )
Piaggio & C SPA(PIA       )
Maire Tecnimont SPA(MT        )
Cie de L'Odet SE(ODET      )
Basilea Pharmaceutica AG(BSLN      )
Go-Ahead Group plc(GOG       )
EFG International AG(EFGN      )
BayWa AG(BYW6      )
Bell Food Group AG(BELL      )
AmRest Holdings SE(EAT       )
Global Dominion Access SA(DOM       )
Takkt AG(TTK       )
CGG SA(CGG       )
SIG plc(SHI       )
Beneteau SA(BEN       )
Grieg Seafood ASA(GSF       )
X-Fab Silicon Foundries SE(XFAB      )
Devro plc(DVO       )
SGL Carbon SE(SGL       )
Ascom Holding AG(ASCN      )
Investment AB Oresund(ORES      )
Mersen SA(MRN       )
RAI Way SPA(RWAY      )
ContourGlobal plc(GLO       )
Autoneum Holding AG(AUTN      )
Mithra Pharmaceuticals SA(MITRA     )
Enea SA(ENA       )
Nagarro SE(NA9       )
Jastrzebska Spolka Weglowa SA(JSW       )
LISI(FII       )
TomTom NV(TOM2      )
DO & CO AG(DOC       )
Hamburger Hafen und Logistik AG(HHFA      )
C&C Group plc(CCR       )
Carmila SA(CARM      )
Attendo AB(ATT       )
F-Secure Oyj(FSC1V     )
Raisio Oyj(RAIVV     )
Alm Brand A/S(ALMB      )
Rank Group plc(RNK       )
DNO ASA(DNO       )
Hensoldt AG(HAG       )
Scandic Hotels Group AB(SHOT      )
Danieli & C Officine Meccaniche SPA(DAN       )
CLS Holdings plc(CLI       )
Econocom Group SA/NV(ECONB     )
Tod's SPA(TOD       )
Credito Emiliano SPA(CE        )
u-blox Holding AG(UBXN      )
Cementir Holding NV(CEM       )
Biesse SPA(BSS       )
Vossloh AG(VOS       )
CIR SpA-Compagnie Industriali(CIR       )
Camurus AB(CAMX      )
ElringKlinger AG(ZIL2      )
Vallourec SA(VK        )
Ypsomed Holding AG(YPSN      )
Altri SGPS SA(ALTR      )
Koenig & Bauer AG(SKB       )
Saras SPA(SRS       )
Italmobiliare SPA(ITM       )
BW LPG Ltd.(BWLPG     )
Corticeira Amorim SGPS SA(COR       )
Hunting plc(HTG       )
Finnair Oyj(FIA1S     )
Manitou BF SA(MTU       )
Datalogic SPA(DAL       )
Palfinger AG(PAL       )
SMA Solar Technology AG(S92       )
Orange Belgium SA(OBEL      )
Wuestenrot & Wuerttembergische AG(WUW       )
Juventus Football Club SPA(JUVE      )
Stagecoach Group plc(SGC       )
Vastned Retail NV(VASTN     )
Karo Pharma AB(KARO      )
Clas Ohlson AB(CLAS B    )
Hexagon Composites ASA(HEX       )
Sagax AB(SAGA D    )
Banca IFIS SPA(IF        )
Steico SE(ST5       )
Wallenius Wilhelmsen ASA(WAWI      )
Altarea SCA(ALTA      )
Fincantieri SPA(FCT       )
Schoeller-Bleckmann Oilfield Equipment AG(SBO       )
Petrofac Ltd.(PFC       )
Telefonaktiebolaget LM Ericsson Class A(ERIC A    )
Pharmagest Inter@ctive(PHA       )
Collector AB(COLL      )
Sparebank 1 Oestlandet(SPOL      )
Banca Monte dei Paschi di Siena SPA(BMPS      )
Bank Handlowy w Warszawie SA(BHW       )
Micro Focus International plc ADR(MFGP      )
Norway Royal Salmon ASA(NRS       )
Ence Energia y Celulosa SA(ENC       )
Corem Property Group AB Preference Shares(CORE PREF )
Vilmorin & Cie SA(RIN       )
Metrovacesa SA(MVC       )
Bonduelle SCA(BON       )
Distribuidora Internacional de Alimentacion SA(DIA       )
Sartorius AG(SRT       )
Funding Circle Holdings plc(FCH       )
Implenia AG(IMPN      )
Prosegur Cash SA(CASH      )
Grupa Azoty SA(ATT       )
Fagerhult AB(FAG       )
Albioma SA(ABIO      )
Lar Espana Real Estate Socimi SA(LRE       )
Atresmedia Corp. de Medios de Comunicacion SA(A3M       )
Oncopeptides AB(ONCO      )
Ciech SA(CIE       )
Flughafen Wien AG(FLU       )
Hornbach Baumarkt AG(HBM       )
Tecnicas Reunidas SA(TRE       )
Hiag Immobilien Holding AG(HIAG      )
Stolt-Nielsen Ltd.(SNI       )
Immobiliare Grande Distribuzione SIIQ SPA(IGD       )
Arnoldo Mondadori Editore SPA(MN        )
Bertrandt AG(BDT       )
VP Bank AG(VPBN      )
Jacquet Metal Service SA(JCQ       )
Oriola Oyj(OKDBV     )
Bakkavor Group plc(BAKK      )
Brunel International NV(BRNL      )
GAM Holding AG(GAM       )
TLG Immobilien AG(TLG       )
Adapteo Oyj(ADAPT     )
BW Offshore Ltd.(BWO       )
Warsaw Stock Exchange(GPW       )
Promotora de Informaciones SA(PRS       )
CropEnergies AG(CE2       )
Agrana Beteiligungs AG(AGR       )
Tarkett SA(TKTT      )
B&S Group Sarl(BSGR      )
APG SGA SA(APGN      )
AKWEL(AKW       )
Eurocash SA(EUR       )
Svenska Handelsbanken AB Class B(SHB B     )
GL Events(GLO       )
Alfa Financial Software Holdings plc(ALFA      )
Guerbet(GBT       )
Aker Horizons Holding ASA(AKH       )
Schmolz + Bickenbach AG(STLN      )
Corestate Capital Holding SA(CCAP      )
BW Energy Ltd.(BWE       )
Porr Ag(POS       )
Aker Carbon Capture ASA(ACC       )
ForFarmers NV(FFARM     )
Ocean Yield ASA(OCY       )
ID Logistics Group(IDL       )
Van de Velde NV(VAN       )
Rallye SA(RAL       )
Mercator Medical SA(MRC       )
Boiron SA(BOI       )
SMCP SA(SMCP      )
Etablissements Maurel et Prom SA(MAU       )
Mota-Engil SGPS SA(EGL       )
DeA Capital SPA(DEA       )
Wereldhave Belgium Comm VA(WEHB      )
Vaccibody AS(VACC      )
NH Hotel Group SA(NHH       )
NCC AB Class A(NCC A     )
Rizzoli Corriere Della Sera Mediagroup SPA(RCS       )
Bourbon Corp.(GBB       )
Union Financiere de France BQE SA(UFF       )
Semapa-Sociedade de Investimento e Gestao(SEM       )
Finablr plc(FIN       )
Intu Properties plc(INTU      )
Aryzta AG(0MFY      )
Annehem Fastigheter AB Class B(ANNE B    )
Greenvolt-Energias Renovaveis SA(GVOLT     )
Thungela Resources Ltd.(TGA       )
Borr Drilling Ltd.(BORR      )
Draegerwerk AG & Co. KGaA(DRW8      )
Irish Bank Resolution Corp. Ltd.(CKL1      )
Carillion plc(CLLN      )
NMC Health plc(NMC       )
"""
